version: "3.8"

services:
  assets_manager:
    image: assets_manager:latest
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 80
    volumes:
      - ${ASSETS_LOCATION}:/root/assets
    env_file:
      - .env
    ports:
      - 7890:80
